augmentation:
  train:
    - name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~

    - name: mosaicdetection
      size: [960, 960]
      affine_scale: [0.9, 1.1]
      mixup_scale: [0.5, 1.5]
      degrees: 0.0
      translate: 0.1
      shear: 0.0
      enable_mixup: true
      mosaic_prob: 1.0
      mixup_prob: 0.15
      fill: 114
      mosaic_off_duration: 15

    - name: hsvjitter
      hgain: 0.015
      sgain: 0.7
      vgain: 0.4
      p: 1.0

    - name: randomhorizontalflip
      p: 0.5

    - name: totensor
      pixel_range: 1.0

    - name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

    - name: mixing
      p: 0.15

  inference:
    - name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~

    - name: totensor
      pixel_range: 1.0

    - name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]