augmentation:
  train:
    - name: mosaicdetection
      p: 1.0

    - name: hsvjitter
      hgain: 0.015
      sgain: 0.7
      vgain: 0.4
      p: 1.0

    - name: randomhorizontalflip
      p: 0.5

    - name: randomverticalflip
      p: 0.0

    - name: randomresize
      scale_range: [0.9, 1.1]

    - name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~
      resize_criteria: long

    - name: totensor
      pixel_range: 1.0

    - name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

    - name: mixing
      p: 0.15

  inference:
    - name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~
      resize_criteria: long

    - name: totensor
      pixel_range: 1.0

    - name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]