augmentation:
  train:
    - name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~
      resize_criteria: long

    - name: randomhorizontalflip
      p: 0.5

    - name: randomverticalflip
      p: 0.0

    - name: hsvjitter
      h_mag: 5
      s_mag: 30
      v_mag: 30

    - name: randomresize
      base_size: [960,960]
      stride: 32
      random_range: 5
      interpolation: bilinear

    - name: randomzoomout
      p: 0.1

    - name: randomioucrop
      p: 0.2

    - name: mosaicdetection
      mosaic_prob: 1.0
      size: [960,960]
      fill: 0

    - name: totensor
      pixel_range: 1.0

    - name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  inference:
    - name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~
      resize_criteria: long

    - name: totensor
      pixel_range: 1.0

    - name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]