augmentation:
  train:
    - name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~

    - name: randomhorizontalflip
      prob: 0.5

    - name: randomverticalflip
      prob: 0.0

    - name: hsvjitter
      hgain: 0.015
      sgain: 0.7
      vgain: 0.4
      prob: 1.0

    - name: randomresize
      scale_range: [0.9, 1.1]

    - name: randomzoomout
      prob: 0.1

    - name: randomioucrop
      prob: 0.2

    - name: mosaicdetection
      prob: 1.0

    - name: totensor
      pixel_range: 1.0

    - name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

    - name: mixing
      prob: 0.15

  inference:
    -
      name: resize
      size: [960, 960]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~

    -
      name: totensor
      pixel_range: 1.0

    -
      name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]